### ISSUE TITLE
The model was not generating more than few tokens! Generation Issue

### ISSUE THREAD

**Issue by Lsayan** [OrangeInSouth/DeePEn#4]
It is a nice work. I was trying the code but then I was having some issue while generating the output. I would be really grateful if authors can look into this issue as soon as possible. I have explained my issue below.

The model was not generating the complete answer and was stopping was generating few tokens. I kept max_new_tokens = 1024 in the config file but still it was not giving. Attaching few examples for the same.
![image](https://github.com/user-attachments/assets/193816f8-2ed1-4d69-bdf7-9ce98428b68c)

The model is not generating the complete output and stopping mid way. Below I have attached the screenshot.
![image](https://github.com/user-attachments/assets/515c26e7-6e12-42b9-9a3e-c30dd5321570)

**Comment by OrangeInSouth** [comment]
Sorry for the late reply, and thanks for your interest in our work.

This issue is caused by the early stop string, which is a hyper-parameter in our work.
You can easily change this parameter by modify your configuration file.

For example, you can remove the line 38 of the file: confs/TriviaQA/LLaMA+Mistral.json

**Comment by Lsayan** [comment]
Thanks for your response. I will look up. 
We are actually working with your code. In case any further issues arise, I will let you know
